### ISSUE TITLE
Crash when defining sign-on policy action

### ISSUE THREAD

**Issue by milocarbol** [pingidentity/terraform-provider-pingone#408]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### PingOne Terraform provider Version
0.15.1

### Terraform Version
1.4.6

### Affected Resource(s)
- pingone_sign_on_policy_action

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    pingone = {
      source  = "pingidentity/pingone"
    }
  }
}

locals  {
  region = "NorthAmerica"
}

variable "admin_environment_id" {
  type = string
}

variable "admin_username" {
  type = string
}

variable "admin_password" {
  type = string
  sensitive = true
}

variable "license_id" {
  type = string
}

variable "terraform_environment_id" {
  type = string
}

variable "terraform_client_id" {
  type = string
}

variable "terraform_client_secret" {
  type = string
  sensitive = true
}

provider "pingone" {
  client_id      = var.terraform_client_id
  client_secret  = var.terraform_client_secret
  environment_id = var.terraform_environment_id
  region         = local.region

  force_delete_production_type = false
}

resource "pingone_environment" "mfa_env" {
  name        = "P1MFA Terraform Lab"
  description = "P1MFA deployed with Terraform"
  type        = "SANDBOX"
  license_id  = var.license_id

  default_population {
    name        = "All Users"
    description = "all users"
  }

  service {
    type = "SSO"
  }

  service {
    type = "MFA"
  }
}

data "pingone_role" "identity_data_admin" {
  name = "Identity Data Admin"
}


data "pingone_role" "environment_admin" {
  name = "Environment Admin"
}

data "pingone_user" "admin_user" {
  environment_id = var.admin_environment_id
  username = var.admin_username
}

resource "pingone_role_assignment_user" "admin_sso_identity_admin" {
  environment_id       = var.admin_environment_id
  user_id              = data.pingone_user.admin_user.id
  role_id              = data.pingone_role.identity_data_admin.id
  scope_environment_id = pingone_environment.mfa_env.id
}

resource "pingone_mfa_policy" "mfa_policy" {
  environment_id = pingone_environment.mfa_env.id
  name           = "MFA Policy"

  mobile {
    enabled = false
  }

  totp {
    enabled = true
  }

  security_key {
    enabled = true
  }

  platform {
    enabled = true
  }

  sms {
    enabled = true
  }

  voice {
    enabled = true
  }

  email {
    enabled = true
  }
}

resource "pingone_sign_on_policy" "mfa_only_sop" {
  environment_id = pingone_environment.mfa_env.id

  name        = "MFA_Only"
  description = "Only includes MFA so that it can be used by the P1MFA adapter"
}

resource "pingone_sign_on_policy_action" "mfa_only_sop_action_1" {
  environment_id    = pingone_environment.mfa_env.id
  sign_on_policy_id = pingone_sign_on_policy.mfa_only_sop.id

  priority = 1

  conditions {
    
    last_sign_on_older_than_seconds = 1
    
    ip_reputation_high_risk      = true
    geovelocity_anomaly_detected = true
    anonymous_network_detected   = true

    user_attribute_equals {
      attribute_reference = "$${user.mfaEnabled}"
      value_boolean       = true
    }

    user_attribute_equals {
      attribute_reference = "$${user.lifecycle.status}"
      value               = "ACCOUNT_OK"
    }
  }

  mfa {
    device_sign_on_policy_id = pingone_mfa_policy.mfa_policy.id
    no_device_mode           = "BYPASS"
  }
}

resource "pingone_application" "mfa_app" {
  environment_id = pingone_environment.mfa_env.id
  name           = "Used by PingFederate"
  enabled        = true

  oidc_options {
    type                        = "WEB_APP"
    grant_types                 = ["AUTHORIZATION_CODE"]
    response_types              = ["CODE"]
    token_endpoint_authn_method = "CLIENT_SECRET_BASIC"
    redirect_uris               = ["https://console.pingone.com"]
  }
}

resource "pingone_application_sign_on_policy_assignment" "mfa_policy_to_app" {
  environment_id = pingone_environment.mfa_env.id
  application_id = pingone_application.mfa_app.id

  sign_on_policy_id = pingone_sign_on_policy.mfa_only_sop.id

  priority = 1
}
```

### Debug Output
See attached 
[debug-output.log](https://github.com/pingidentity/terraform-provider-pingone/files/11708943/debug-output.log)

### Panic Output
See attached

### Expected Behavior
No crash

### Actual Behavior
Crash

### Steps to Reproduce
1. terraform apply -var...

### Important Factoids
I think this is just an issue with my code so I'm just reporting this for the crash.

**Comment by patrickcping** [comment]
Thanks for raising @milocarbol !  First glance nothing jumps out as being incorrect, but a panic crash will always be a bug in the code.  Will look to fix for the next release

**Comment by milocarbol** [comment]
Removing these blocks from the sign-on policy action fixed it.
```
user_attribute_equals {
      attribute_reference = "$${user.mfaEnabled}"
      value_boolean       = true
    }

    user_attribute_equals {
      attribute_reference = "$${user.lifecycle.status}"
      value               = "ACCOUNT_OK"
    }
```

They're documented here though: https://registry.terraform.io/providers/pingidentity/pingone/latest/docs/resources/sign_on_policy_action#example-usage---mfa

**Comment by patrickcping** [comment]
@milocarbol I see the problem - there a few issues here:

1. Your HCL - because the MFA sign-on policy action has `priority = 1`, the `user_attribute_equals` actually won't be able to evaluate during login, and the provider code is meant to catch this situation (see point 3 below).  This is consistent with the console, where the user attribute evaluation fields are hidden if MFA is the first action in the policy.  For the `user_attribute_equals` conditions, you'll need a `login` or `identifier_first` action as priority 1 instead, but as you have an MFA only policy the `user_attribute_equals` conditions can be safely removed.

2. Documentation - the docs will need to improve to call out the above case, we'll use this issue to track that update.

3. The provider code:
  1. The provider does catch the situation that the `user_attribute_equals` is being set on a `priority = 1` policy action, but is incorrectly setting it as a warning and not an error, leading to the crash we see.  This will be fixed as a bug.
  2. The provider should actually warn about this on the `plan` phase as a schema validation, instead of erroring out in the `apply` phase.  So this will be an enhancement also tracked in this issue.

**Comment by patrickcping** [comment]
Remedial work has now been merged into main.  Because of limitations in Terraform's SDKv2 we're not able to detect and warn of this issue on `plan` until we upgrade the resource to Terraform's plugin framework SDK.  For now though, the provider responds with an appropriate error on `apply` instead of the panic.
