### ISSUE TITLE
Cannot import pingone_application with oidc_options

### ISSUE THREAD

**Issue by Shocktrooper** [pingidentity/terraform-provider-pingone#760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### PingOne Terraform provider Version
0.26.1

### Terraform Version
1.6.1

### Affected Resource(s)
pingone_application

### Terraform Configuration Files
```hcl
resource "pingone_application" "terraform_admin_app_management" {
  name           = "Terraform App Admin"
  environment_id = pingone_environment.admin.id
  enabled        = true
  oidc_options {
    redirect_uris               = ["https://localhost:3000"]
    type                        = "WORKER"
    grant_types                 = ["CLIENT_CREDENTIALS"]
    token_endpoint_authn_method = "CLIENT_SECRET_BASIC"
  }
}

import {
  to = pingone_application.terraform_admin_app_management 
  id = "123456/123456"
}

```

### Expected Behavior
Resource should have imported

### Actual Behavior
```Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Error when calling `ReadApplicationSecret`: The request could not be completed. You do not have access to this resource.
│
│ PingOne Error Details:
│ ID: 123456
│ Code: ACCESS_FAILED
│ Message: The request could not be completed. You do not have access to this
│ resource.
│ Details object: [{"code":"INSUFFICIENT_PERMISSIONS","message":"Actor does
│ not have permissions to access worker application client secrets"}]
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
I have tried alternate configuration methods for the provider.  ClientID/Secret and Access token.  None of these methods allow the retrieval of the client secret.  It appears that the API does allow an access token to retrieve the secret but this might not be utilized for importing.

I have also created a separate worker application just for accessing the admin client_secret and this still did not work

https://apidocs.pingidentity.com/pingone/platform/v1/api/#post-token-admin-app-client_credentials
https://apidocs.pingidentity.com/pingone/platform/v1/api/#get-read-application-secret

**Comment by patrickcping** [comment]
hi @Shocktrooper thanks for raising!  This can be due to role permission setup, but we're aware of a potential issue in this area.

**Role Permissions**
Does the worker application that is attempting to import the secret of the `Terraform App Admin` worker have lesser role permissions?  For example, the import worker application may have "Environment Admin" scoped to the `pingone_environment.admin.id` environment, but the `Terraform App Admin` worker has "Environment Admin" scoped to the organisation.
In this case, there is a risk of privilege escalation and the secret will not be available to the import worker application.

If you post here the admin role permissions assigned to the worker application attempting import, and the admin role permissions of the `Terraform App Admin`, I can advise if this is the case.

**Potential Issue**
We've seen cases where the `Terraform App Admin` worker temporarily makes the secret unavailable after it's used to create a new environment.  This might resolve after a period of inactivity, which can be one or two hours, after which the secret is available again.

To verify this, you'd see the error you're reporting on import after creation of PingOne configuration, you'd leave the worker application unused for a period of time (give it a few hours) and then re-run the same HCL.  If the import is successful after leaving the application unused, then we know to advance this investigation on the API.

**Comment by Shocktrooper** [comment]
So I have a workaround but it requires double applies and it was the issue you mentioned where the worker app that was meant to manage the administrator app had less permissions.  To resolve this I have a permissions assignment that adds back the permissions to the worker app on the second apply so that the permissions of the worker will match the admin app thus.  This is not really possible without great difficulty with the first apply if there is something like a new environment created that the admin app creates as there is a bit of a dependency ordering issue.  We could use a depends on but this would get quite complicated to maintain as each new object that resulted in new permissions (E.G. a population, environment) would need a new depends on record.

**Comment by patrickcping** [comment]
In the upcoming `v1.0` release the client secret is being de-coupled from the `pingone_application` resource, so the ability to import an application won't be hindered by the inability to read the client secret.  This will solve the case where the admin doesn't/shouldn't have access to the secret but still should manage the application configuration.

There is the case the admin should be able to still manage the client secret, so it pushes the problem to the `pingone_application_secret` resource.  In this case, we'll be issuing better guidance on how to manage role assignment when the worker creates new environments (essentially causing difference in role assignment between the worker app and the admin users)

**Comment by Shocktrooper** [comment]
@patrickcping Where are the docs added for the new guidance?

**Comment by patrickcping** [comment]
@Shocktrooper The guide has been merged into the main code line which closes this issue.  You'll be able to see the guide on the registry once I release `v1.0.0-rc1`.

`v1.0.0-rc1` itself is a release candidate build and isn't yet ready for production use.  That will come with the full `v1.0.0` release later. 

Additionally, there isn't a requirement to upgrade your HCL to use the `v1.*` version for any of the details in the guide

**Comment by patrickcping** [comment]
For completeness: https://registry.terraform.io/providers/pingidentity/pingone/latest/docs/guides/admin-role-management
